/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AppRouteImport } from './routes/app'
import { Route as CreateWorkspaceRouteImport } from './routes/create-workspace'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminComputeRouteImport } from './routes/admin.compute'
import { Route as AdminDatasetsRouteImport } from './routes/admin.datasets'
import { Route as AdminDeploymentsRouteImport } from './routes/admin.deployments'
import { Route as AdminExperimentsRouteImport } from './routes/admin.experiments'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminPredictionsRouteImport } from './routes/admin.predictions'
import { Route as AdminRunsRouteImport } from './routes/admin.runs'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsageRouteImport } from './routes/admin.usage'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCompareRouteImport } from './routes/app.compare'
import { Route as AppDeploymentsRouteImport } from './routes/app.deployments'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as AppScalingRouteImport } from './routes/app.scaling'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppValidationRouteImport } from './routes/app.validation'
import { Route as AppDatasetsIndexRouteImport } from './routes/app.datasets.index'
import { Route as AppDatasetsIdRouteImport } from './routes/app.datasets.$id'
import { Route as AppExperimentsIndexRouteImport } from './routes/app.experiments.index'
import { Route as AppExperimentsIdRouteImport } from './routes/app.experiments.$id'
import { Route as AppExperimentsNewRouteImport } from './routes/app.experiments.new'
import { Route as AppModelsIndexRouteImport } from './routes/app.models.index'
import { Route as AppModelsIdRouteImport } from './routes/app.models.$id'
import { Route as AppPredictionsIndexRouteImport } from './routes/app.predictions.index'
import { Route as AppPredictionsIdRouteImport } from './routes/app.predictions.$id'
import { Route as AppRunsIndexRouteImport } from './routes/app.runs.index'
import { Route as AppRunsIdRouteImport } from './routes/app.runs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWorkspaceRoute = CreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComputeRoute = AdminComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDatasetsRoute = AdminDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeploymentsRoute = AdminDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExperimentsRoute = AdminExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPredictionsRoute = AdminPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunsRoute = AdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsageRoute = AdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppDeploymentsRoute = AppDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppScalingRoute = AppScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppValidationRoute = AppValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsIndexRoute = AppDatasetsIndexRouteImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsIdRoute = AppDatasetsIdRouteImport.update({
  id: '/datasets/$id',
  path: '/datasets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsIndexRoute = AppExperimentsIndexRouteImport.update({
  id: '/experiments/',
  path: '/experiments/',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsIdRoute = AppExperimentsIdRouteImport.update({
  id: '/experiments/$id',
  path: '/experiments/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsNewRoute = AppExperimentsNewRouteImport.update({
  id: '/experiments/new',
  path: '/experiments/new',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsIndexRoute = AppModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsIdRoute = AppModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsIndexRoute = AppPredictionsIndexRouteImport.update({
  id: '/predictions/',
  path: '/predictions/',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictionsIdRoute = AppPredictionsIdRouteImport.update({
  id: '/predictions/$id',
  path: '/predictions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/create-workspace': typeof CreateWorkspaceRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/compute': typeof AdminComputeRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/experiments': typeof AdminExperimentsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/compare': typeof AppCompareRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/research': typeof AppResearchRoute
  '/app/scaling': typeof AppScalingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/validation': typeof AppValidationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
  '/app/experiments/new': typeof AppExperimentsNewRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/predictions/$id': typeof AppPredictionsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/datasets/': typeof AppDatasetsIndexRoute
  '/app/experiments/': typeof AppExperimentsIndexRoute
  '/app/models/': typeof AppModelsIndexRoute
  '/app/predictions/': typeof AppPredictionsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/create-workspace': typeof CreateWorkspaceRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/compute': typeof AdminComputeRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/experiments': typeof AdminExperimentsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/compare': typeof AppCompareRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/research': typeof AppResearchRoute
  '/app/scaling': typeof AppScalingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/validation': typeof AppValidationRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
  '/app/experiments/new': typeof AppExperimentsNewRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/predictions/$id': typeof AppPredictionsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/datasets': typeof AppDatasetsIndexRoute
  '/app/experiments': typeof AppExperimentsIndexRoute
  '/app/models': typeof AppModelsIndexRoute
  '/app/predictions': typeof AppPredictionsIndexRoute
  '/app/runs': typeof AppRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/app': typeof AppRouteWithChildren
  '/create-workspace': typeof CreateWorkspaceRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/compute': typeof AdminComputeRoute
  '/admin/datasets': typeof AdminDatasetsRoute
  '/admin/deployments': typeof AdminDeploymentsRoute
  '/admin/experiments': typeof AdminExperimentsRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/predictions': typeof AdminPredictionsRoute
  '/admin/runs': typeof AdminRunsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/usage': typeof AdminUsageRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/compare': typeof AppCompareRoute
  '/app/deployments': typeof AppDeploymentsRoute
  '/app/research': typeof AppResearchRoute
  '/app/scaling': typeof AppScalingRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/validation': typeof AppValidationRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/experiments/$id': typeof AppExperimentsIdRoute
  '/app/experiments/new': typeof AppExperimentsNewRoute
  '/app/models/$id': typeof AppModelsIdRoute
  '/app/predictions/$id': typeof AppPredictionsIdRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/app/datasets/': typeof AppDatasetsIndexRoute
  '/app/experiments/': typeof AppExperimentsIndexRoute
  '/app/models/': typeof AppModelsIndexRoute
  '/app/predictions/': typeof AppPredictionsIndexRoute
  '/app/runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/create-workspace'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/research'
    | '/signup'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/compute'
    | '/admin/datasets'
    | '/admin/deployments'
    | '/admin/experiments'
    | '/admin/health'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/predictions'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/app/compare'
    | '/app/deployments'
    | '/app/research'
    | '/app/scaling'
    | '/app/settings'
    | '/app/usage'
    | '/app/validation'
    | '/admin/'
    | '/app/'
    | '/app/datasets/$id'
    | '/app/experiments/$id'
    | '/app/experiments/new'
    | '/app/models/$id'
    | '/app/predictions/$id'
    | '/app/runs/$id'
    | '/app/datasets/'
    | '/app/experiments/'
    | '/app/models/'
    | '/app/predictions/'
    | '/app/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/create-workspace'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/research'
    | '/signup'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/compute'
    | '/admin/datasets'
    | '/admin/deployments'
    | '/admin/experiments'
    | '/admin/health'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/predictions'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/app/compare'
    | '/app/deployments'
    | '/app/research'
    | '/app/scaling'
    | '/app/settings'
    | '/app/usage'
    | '/app/validation'
    | '/admin'
    | '/app'
    | '/app/datasets/$id'
    | '/app/experiments/$id'
    | '/app/experiments/new'
    | '/app/models/$id'
    | '/app/predictions/$id'
    | '/app/runs/$id'
    | '/app/datasets'
    | '/app/experiments'
    | '/app/models'
    | '/app/predictions'
    | '/app/runs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/app'
    | '/create-workspace'
    | '/docs'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/research'
    | '/signup'
    | '/verify-email'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/compute'
    | '/admin/datasets'
    | '/admin/deployments'
    | '/admin/experiments'
    | '/admin/health'
    | '/admin/models'
    | '/admin/organizations'
    | '/admin/predictions'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/usage'
    | '/admin/users'
    | '/app/compare'
    | '/app/deployments'
    | '/app/research'
    | '/app/scaling'
    | '/app/settings'
    | '/app/usage'
    | '/app/validation'
    | '/admin/'
    | '/app/'
    | '/app/datasets/$id'
    | '/app/experiments/$id'
    | '/app/experiments/new'
    | '/app/models/$id'
    | '/app/predictions/$id'
    | '/app/runs/$id'
    | '/app/datasets/'
    | '/app/experiments/'
    | '/app/models/'
    | '/app/predictions/'
    | '/app/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AppRoute: typeof AppRouteWithChildren
  CreateWorkspaceRoute: typeof CreateWorkspaceRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResearchRoute: typeof ResearchRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-workspace': {
      id: '/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof CreateWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compute': {
      id: '/admin/compute'
      path: '/compute'
      fullPath: '/admin/compute'
      preLoaderRoute: typeof AdminComputeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/datasets': {
      id: '/admin/datasets'
      path: '/datasets'
      fullPath: '/admin/datasets'
      preLoaderRoute: typeof AdminDatasetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deployments': {
      id: '/admin/deployments'
      path: '/deployments'
      fullPath: '/admin/deployments'
      preLoaderRoute: typeof AdminDeploymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experiments': {
      id: '/admin/experiments'
      path: '/experiments'
      fullPath: '/admin/experiments'
      preLoaderRoute: typeof AdminExperimentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/predictions': {
      id: '/admin/predictions'
      path: '/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AdminPredictionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/runs': {
      id: '/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usage': {
      id: '/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deployments': {
      id: '/app/deployments'
      path: '/deployments'
      fullPath: '/app/deployments'
      preLoaderRoute: typeof AppDeploymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scaling': {
      id: '/app/scaling'
      path: '/scaling'
      fullPath: '/app/scaling'
      preLoaderRoute: typeof AppScalingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/validation': {
      id: '/app/validation'
      path: '/validation'
      fullPath: '/app/validation'
      preLoaderRoute: typeof AppValidationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets/': {
      id: '/app/datasets/'
      path: '/datasets'
      fullPath: '/app/datasets/'
      preLoaderRoute: typeof AppDatasetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets/$id': {
      id: '/app/datasets/$id'
      path: '/datasets/$id'
      fullPath: '/app/datasets/$id'
      preLoaderRoute: typeof AppDatasetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments/': {
      id: '/app/experiments/'
      path: '/experiments'
      fullPath: '/app/experiments/'
      preLoaderRoute: typeof AppExperimentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments/$id': {
      id: '/app/experiments/$id'
      path: '/experiments/$id'
      fullPath: '/app/experiments/$id'
      preLoaderRoute: typeof AppExperimentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/experiments/new': {
      id: '/app/experiments/new'
      path: '/experiments/new'
      fullPath: '/app/experiments/new'
      preLoaderRoute: typeof AppExperimentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models/': {
      id: '/app/models/'
      path: '/models'
      fullPath: '/app/models/'
      preLoaderRoute: typeof AppModelsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models/$id': {
      id: '/app/models/$id'
      path: '/models/$id'
      fullPath: '/app/models/$id'
      preLoaderRoute: typeof AppModelsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions/': {
      id: '/app/predictions/'
      path: '/predictions'
      fullPath: '/app/predictions/'
      preLoaderRoute: typeof AppPredictionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/predictions/$id': {
      id: '/app/predictions/$id'
      path: '/predictions/$id'
      fullPath: '/app/predictions/$id'
      preLoaderRoute: typeof AppPredictionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/': {
      id: '/app/runs/'
      path: '/runs'
      fullPath: '/app/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminComputeRoute: typeof AdminComputeRoute
  AdminDatasetsRoute: typeof AdminDatasetsRoute
  AdminDeploymentsRoute: typeof AdminDeploymentsRoute
  AdminExperimentsRoute: typeof AdminExperimentsRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPredictionsRoute: typeof AdminPredictionsRoute
  AdminRunsRoute: typeof AdminRunsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsageRoute: typeof AdminUsageRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminComputeRoute: AdminComputeRoute,
  AdminDatasetsRoute: AdminDatasetsRoute,
  AdminDeploymentsRoute: AdminDeploymentsRoute,
  AdminExperimentsRoute: AdminExperimentsRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPredictionsRoute: AdminPredictionsRoute,
  AdminRunsRoute: AdminRunsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsageRoute: AdminUsageRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCompareRoute: typeof AppCompareRoute
  AppDeploymentsRoute: typeof AppDeploymentsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppScalingRoute: typeof AppScalingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppValidationRoute: typeof AppValidationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDatasetsIdRoute: typeof AppDatasetsIdRoute
  AppExperimentsIdRoute: typeof AppExperimentsIdRoute
  AppExperimentsNewRoute: typeof AppExperimentsNewRoute
  AppModelsIdRoute: typeof AppModelsIdRoute
  AppPredictionsIdRoute: typeof AppPredictionsIdRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  AppDatasetsIndexRoute: typeof AppDatasetsIndexRoute
  AppExperimentsIndexRoute: typeof AppExperimentsIndexRoute
  AppModelsIndexRoute: typeof AppModelsIndexRoute
  AppPredictionsIndexRoute: typeof AppPredictionsIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompareRoute: AppCompareRoute,
  AppDeploymentsRoute: AppDeploymentsRoute,
  AppResearchRoute: AppResearchRoute,
  AppScalingRoute: AppScalingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppValidationRoute: AppValidationRoute,
  AppIndexRoute: AppIndexRoute,
  AppDatasetsIdRoute: AppDatasetsIdRoute,
  AppExperimentsIdRoute: AppExperimentsIdRoute,
  AppExperimentsNewRoute: AppExperimentsNewRoute,
  AppModelsIdRoute: AppModelsIdRoute,
  AppPredictionsIdRoute: AppPredictionsIdRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  AppDatasetsIndexRoute: AppDatasetsIndexRoute,
  AppExperimentsIndexRoute: AppExperimentsIndexRoute,
  AppModelsIndexRoute: AppModelsIndexRoute,
  AppPredictionsIndexRoute: AppPredictionsIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AppRoute: AppRouteWithChildren,
  CreateWorkspaceRoute: CreateWorkspaceRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResearchRoute: ResearchRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
